<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H2ULFNK" failures="2" tests="10" name="Test" time="0.277" errors="0" timestamp="2020-09-26T08:26:12 IST">
  <testcase classname="Test001" name="Test1" time="0.031">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="Test001" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="Test001" name="Test1" time="0.005">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="Test001" name="Test1" time="0.012">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="Test001" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test001.Test1(Test001.java:8)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="Test001" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Test001" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Test001" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Test001" name="Test2" time="0.007">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="Test001" name="Test2" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test001.Test2(Test001.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test -->
